#!/usr/bin/env bash
# Generate placement evidence artefacts for QuantForge.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

QF="${QUANTFORGE_BIN:-./build/quantforge}"
REPLAY="${LOB_REPLAY_BIN:-./build/lob_replay_export}"
OUT=build/reports
mkdir -p "$OUT" web/replay

"$QF" --config configs/default_experiment.json --out-dir "$OUT" --json-out "$OUT/default_comparison.json"
"$QF" --config configs/walk_forward.json --out-dir "$OUT" --json-out "$OUT/walk_forward.json"
"$QF" --config configs/stress_cancel_race.json --out-dir "$OUT" --json-out "$OUT/stress_cancel_race.json"
"$QF" --config configs/stress_vol_spike.json --out-dir "$OUT" --json-out "$OUT/stress_vol_spike.json"
"$QF" --config configs/stress_stale_quotes.json --out-dir "$OUT" --json-out "$OUT/stress_stale_quotes.json"
"$QF" --config configs/stress_toxic_flow.json --out-dir "$OUT" --json-out "$OUT/stress_toxic_flow.json"
"$REPLAY" --strategy avellaneda_stoikov --horizon 1200 --out web/replay/sample_replay.json

cat > "$OUT/BENCHMARK.md" <<'EOF'
# QuantForge benchmark / evidence snapshot

Generated by `scripts/generate_evidence.sh`.

| Artefact | Path |
|----------|------|
| Default MM comparison | `build/reports/default_comparison.json` |
| Walk-forward | `build/reports/walk_forward.json` |
| Cancel-race stress | `build/reports/stress_cancel_race.json` |
| Vol-spike stress | `build/reports/stress_vol_spike.json` |
| Stale-quote stress | `build/reports/stress_stale_quotes.json` |
| Toxic-flow stress | `build/reports/stress_toxic_flow.json` |
| LOB replay | `web/replay/sample_replay.json` |

## How to demo

1. `ctest --test-dir build --output-on-failure`
2. Research UI: `cd python && uvicorn quantforge_research.app:app --port 8000`
3. Replay: http://127.0.0.1:8000/replay/
4. Narrate leakage foil + kill-switch under stress configs.
EOF

echo "Wrote $OUT/BENCHMARK.md"
echo "Evidence generation complete."
