# Generate placement evidence artefacts for QuantForge.
# Prerequisites: built binaries under build/ (or set QUANTFORGE_BIN / LOB_REPLAY_BIN).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$qf = if ($env:QUANTFORGE_BIN) { $env:QUANTFORGE_BIN } else { Join-Path $Root "build\quantforge.exe" }
if (-not (Test-Path $qf)) { $qf = Join-Path $Root "build\quantforge" }
$replay = if ($env:LOB_REPLAY_BIN) { $env:LOB_REPLAY_BIN } else { Join-Path $Root "build\lob_replay_export.exe" }
if (-not (Test-Path $replay)) { $replay = Join-Path $Root "build\lob_replay_export" }

$out = Join-Path $Root "build\reports"
New-Item -ItemType Directory -Force -Path $out | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root "web\replay") | Out-Null

Write-Host "== default comparison =="
& $qf --config configs/default_experiment.json --out-dir $out --json-out (Join-Path $out "default_comparison.json")

Write-Host "== walk-forward =="
& $qf --config configs/walk_forward.json --out-dir $out --json-out (Join-Path $out "walk_forward.json")

Write-Host "== stress cancel race =="
& $qf --config configs/stress_cancel_race.json --out-dir $out --json-out (Join-Path $out "stress_cancel_race.json")

Write-Host "== stress vol spike =="
& $qf --config configs/stress_vol_spike.json --out-dir $out --json-out (Join-Path $out "stress_vol_spike.json")

Write-Host "== stress stale quotes =="
& $qf --config configs/stress_stale_quotes.json --out-dir $out --json-out (Join-Path $out "stress_stale_quotes.json")

Write-Host "== stress toxic flow =="
& $qf --config configs/stress_toxic_flow.json --out-dir $out --json-out (Join-Path $out "stress_toxic_flow.json")

Write-Host "== LOB replay frames =="
& $replay --strategy avellaneda_stoikov --horizon 1200 --out (Join-Path $Root "web\replay\sample_replay.json")

$bench = Join-Path $out "BENCHMARK.md"
@"
# QuantForge benchmark / evidence snapshot

Generated by ``scripts/generate_evidence.ps1``.

| Artefact | Path |
|----------|------|
| Default MM comparison | ``build/reports/default_comparison.json`` |
| Walk-forward | ``build/reports/walk_forward.json`` |
| Cancel-race stress | ``build/reports/stress_cancel_race.json`` |
| Vol-spike stress | ``build/reports/stress_vol_spike.json`` |
| Stale-quote stress | ``build/reports/stress_stale_quotes.json`` |
| Toxic-flow stress | ``build/reports/stress_toxic_flow.json`` |
| LOB replay | ``web/replay/sample_replay.json`` |

## How to demo

1. ``ctest --test-dir build --output-on-failure``
2. Open research UI: ``cd python && uvicorn quantforge_research.app:app --port 8000``
3. Replay: http://127.0.0.1:8000/replay/
4. Narrate leakage foil + kill-switch under ``stress_mm.json`` / ``stress_vol_spike.json``.

"@ | Set-Content -Path $bench -Encoding utf8

Write-Host "Wrote $bench"
Write-Host "Evidence generation complete."
