#include "quantforge/report/comparison_report.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>

namespace quantforge::report {

std::string formatMarkdown(const ResearchReport& report)
{
    std::ostringstream out;
    out << std::fixed << std::setprecision(4);

    out << "# QuantForge Comparison Report\n\n";
    out << "**Experiment:** " << report.experiment.experiment_name << "\n\n";

    out << "## Strategy comparison (LOB fills)\n\n";
    out << "| Strategy | MTM PnL | Inventory | Max DD | Fills | Fill rate | "
           "Spread capture | Adv. selection |\n";
    out << "|---|---:|---:|---:|---:|---:|---:|---:|\n";

    for (const auto& row : report.experiment.results) {
        const auto& m = row.simulation.metrics;
        const auto& s = row.simulation.final_snapshot;
        out << "| " << row.strategy_name
            << " | " << m.mtm_pnl
            << " | " << s.inventory
            << " | " << m.max_drawdown
            << " | " << m.fills
            << " | " << m.fill_rate
            << " | " << m.spread_capture
            << " | " << m.adverse_selection
            << " |\n";
    }

    if (!report.leakage_cases.empty()) {
        out << "\n## Leakage case study (naive bar vs LOB)\n\n";
        out << "Naive bar fills use same-bar close for decision *and* fill "
               "price — a classic look-ahead / fantasy-fill pattern. "
               "LOB path uses the matching engine.\n\n";

        for (const auto& cs : report.leakage_cases) {
            out << "### " << cs.title << "\n\n";
            out << "| Path | Strategy | MTM PnL | Fills | Notes |\n";
            out << "|---|---|---:|---:|---|\n";
            out << "| LOB | " << cs.lob.strategy_name
                << " | " << cs.lob.simulation.metrics.mtm_pnl
                << " | " << cs.lob.simulation.metrics.fills
                << " | realistic matching |\n";
            out << "| Naive bar | " << cs.naive.strategy_name
                << " | " << cs.naive.metrics.mtm_pnl
                << " | " << cs.naive.fantasy_fills
                << " | "
                << (cs.naive.used_look_ahead ? "same-bar close leakage" : "open decision")
                << " |\n\n";
        }
    }

    if (!report.notes.empty()) {
        out << "## Notes\n\n" << report.notes << "\n";
    }

    out << "\n---\n*Generated by QuantForge `report::formatMarkdown`.*\n";
    return out.str();
}

std::string formatCsv(const experiment::ExperimentReport& report)
{
    std::ostringstream out;
    out << std::fixed << std::setprecision(6);
    out << "strategy,mtm_pnl,inventory,max_drawdown,fills,fill_rate,"
           "spread_capture,adverse_selection,events,trades\n";

    for (const auto& row : report.results) {
        const auto& m = row.simulation.metrics;
        const auto& s = row.simulation.final_snapshot;
        out << row.strategy_name << ','
            << m.mtm_pnl << ','
            << s.inventory << ','
            << m.max_drawdown << ','
            << m.fills << ','
            << m.fill_rate << ','
            << m.spread_capture << ','
            << m.adverse_selection << ','
            << row.simulation.events_processed << ','
            << row.simulation.trades << '\n';
    }
    return out.str();
}

void writeReportFiles(
    const ResearchReport& report,
    const std::filesystem::path& markdown_path,
    const std::filesystem::path& csv_path
)
{
    {
        std::ofstream out(markdown_path);
        if (!out) {
            throw std::runtime_error(
                "failed to write markdown report: " + markdown_path.string()
            );
        }
        out << formatMarkdown(report);
    }
    {
        std::ofstream out(csv_path);
        if (!out) {
            throw std::runtime_error(
                "failed to write csv report: " + csv_path.string()
            );
        }
        out << formatCsv(report.experiment);
    }
}

} // namespace quantforge::report
